#!/bin/bash
# ==========================================
# Warna
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
# ==========================================

# Kosongkan file .log
find /var/log/ -type f -name "*.log" | while read -r log; do
  echo "$log clear"
  truncate -s 0 "$log"
done

# Kosongkan file .err
find /var/log/ -type f -name "*.err" | while read -r log; do
  echo "$log clear"
  truncate -s 0 "$log"
done

# Kosongkan file mail.*
find /var/log/ -type f -name "mail.*" | while read -r log; do
  echo "$log clear"
  truncate -s 0 "$log"
done

# Kosongkan log spesifik
for log in /var/log/syslog /var/log/btmp /var/log/messages /var/log/debug; do
  if [ -f "$log" ]; then
    echo "$log clear"
    truncate -s 0 "$log"
  fi
done

echo -e ""
echo -e " ${GREEN}Clear Log Berhasil${NC}"
echo ""
