#!/bin/bash
MYIP=$(curl -sS ipv4.icanhazip.com)
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"

# Warna
GREEN='\033[0;32m'
NC='\033[0m'

function notif_clearcache() {
  echo -e "${GREEN}Notif AddHost Tele${NC}"
  sleep 2
  TEXT="
<code>◇━━━━━━━━━━━━━━◇</code>
<b>  ⚠️CLEAR CACHE NOTIF⚠️</b>
<b>     Clear Cache VPS</b>
<code>◇━━━━━━━━━━━━━━◇</code>
<code>Clear Cache Done</code>
<code>◇━━━━━━━━━━━━━━◇</code>
"
  curl -s --max-time "$TIME" -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" "$URL" >/dev/null
}

loading() {
  local pid=$1
  local delay=0.1
  local spin='-\|/'

  while ps -p "$pid" > /dev/null; do
    local temp=${spin#?}
    printf "[%c] " "$spin"
    spin=$temp${spin%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done
  printf "    \b\b\b\b"
}

# Cek Root
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}This script must be run as root!${NC}"
  exit 1
fi

clear
echo ""
echo ""
echo -e "[ \033[32mInfo\033[0m ] Sync and clear RAM Cache"

# Sync and drop caches safely
sync
echo 1 > /proc/sys/vm/drop_caches

exit 0
