[dr]
type: drive
scope: drive
token: {"access_token":"ya29.a0AQQ_BDSWQIP26FqHvbtXxMuxTWy0liW0Ebe0HAlzm_lTv-3E3Ed4Kuw9JhSXs__mKLT3PInbTbFbGO_5HIpRtFZq_sdaExHYmOAgv4OQ3PIa_EleHS7LRuFCeotzoN9INrWGOFys0IgyQAOKhJjPcBIx_Xk5WsI0fsfeYOGhqxG3q-GgkJ1Qzq6SHBGV1HOXq19ftfMaCgYKASoSARMSFQHGX2MiuQszr61lDTaXT2qOB3w27w0206","token_type":"Bearer","refresh_token":"1//09gyBI_nC6OfWCgYIARAAGAkSNwF-L9IrcTDYaoDXgIWCQ228XzLz0WSi8QbJrSryOy3IEwVY9ou9dtfD_Z1ZK9eze5IMEqsxbi4","expiry":"2025-10-13T02:42:09.21839519Z","expires_in":3599}
