#!/bin/bash
Green="\e[92;1m"
RED="\033[1;31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
NC='\e[0m'
MYIP=$(wget -qO- icanhazip.com);
clear
echo ""
echo ""
echo -e "   ${BLUE}_______________________________$NC"
echo -e "   \e[1;32m  WELCOME TO AUTO POINTING $NC"
echo -e "   ${BLUE}_______________________________$NC"
echo ""
if ! command -v jq &> /dev/null; then
    echo -e "Tunggu sebentar proses. Menginstall Cloudflare..."
    apt install jq -y >/dev/null
else
    echo -e "Cloudflare Terpasang."
fi
if [ ! -s /etc/apicf ]; then
  echo "Token Cloudflare (CF_KEY) tidak ditemukan."
  read -p "Masukkan token Cloudflare Anda (tekan Enter jika ingin membiarkan kosong): " input_token

  if [ -n "$input_token" ]; then
    echo "$input_token" > /etc/apicf
    export CF_KEY="$input_token"
  else
    echo "Tidak ada token dimasukkan, Menghentikan Pointing Domain"
    exit 1
  fi
else
  CF_KEY=$(cat /etc/apicf)
  export CF_KEY
fi
clear
echo -e ""
echo -e "\033[96;1m============================\033[0m"
echo -e "\033[95;1m      INPUT SUBDOMAIN  \033[0m"
echo -e "\033[96;1m============================\033[0m"
echo -e "\033[91;1m Note. contoh domain :\033[0m \033[93m domainkeren.com \033[0m"
echo -e "\033[91;1m Note. contoh Subdomain :\033[0m \033[93m servervip \033[0m"
read -p "DOMAIN    :  " DO
echo -e " "
read -p "SUBDOMAIN :  " SUB
echo -e ""
read -p "IP        :  " IP
echo -e ""
SUB_DOMAIN=${SUB}.${DO}
NS_DOMAIN=*.${SUB_DOMAIN}
set -euo pipefail
echo "Pointing Domain for $SUB_DOMAIN..."
ZONE=$(
		curl -sLX GET "https://api.cloudflare.com/client/v4/zones?name=${DO}&status=active" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" | jq -r .result[0].id
	)

	RECORD=$(
		curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${SUB_DOMAIN}" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" | jq -r .result[0].id
	)

		RECORD1=$(
		curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${NS_DOMAIN}" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" | jq -r .result[0].id
	)

	if [[ "${#RECORD}" -le 10 ]]; then
		RECORD=$(
			curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
			-H "Authorization: Bearer ${CF_KEY}" \
			-H "Content-Type: application/json" \
			--data '{"type":"A","name":"'${SUB_DOMAIN}'","content":"'${IP}'","proxied":false}' | jq -r .result.id
		)
	else
		RESULT=$(
		curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD}" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" \
		--data '{"type":"A","name":"'${SUB_DOMAIN}'","content":"'${IP}'","proxied":false}'
	)
	fi
		
	if [[ "${#RECORD1}" -le 10 ]]; then
		RECORD2=$(
			curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
			-H "Authorization: Bearer ${CF_KEY}" \
			-H "Content-Type: application/json" \
			--data '{"type":"A","name":"'${NS_DOMAIN}'","content":"'${IP}'","proxied":true}' | jq -r .result.id
		)
	else

	RESULT2=$(
		curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD1}" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" \
		--data '{"type":"A","name":"'${NS_DOMAIN}'","content":"'${IP}'","proxied":true}'
	)	
	fi
clear
eval $(wget -qO- "https://raw.githubusercontent.com/Ilham24022001/Gantengzz/main/Fls/botkey")
TIMES="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="_______________________________
  POINTING DOMAIN BERHASIL 
_______________________________
  DOMAIN  : $SUB_DOMAIN 
  WILCARD : $NS_DOMAIN 
  IP      : $IP 
_______________________________
"
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null

echo ""
echo -e "   ${BLUE}_______________________________$NC"
echo -e "   \e[1;32m  POINTING DOMAIN BERHASIL $NC"
echo -e "   ${BLUE}_______________________________$NC"
echo ""
echo -e "   \e[1;32m  DOMAIN  : $SUB_DOMAIN $NC"
echo -e "   \e[1;32m  WILCARD : $NS_DOMAIN $NC"
echo -e "   \e[1;32m  IP      : $IP $NC"
echo ""
echo -e "   ${BLUE}_______________________________$NC"
read -n 1 -s -r -p "Press any key to back on menu"
menu
