#!/bin/bash
# COLOR VALIDATION
clear
c="\033[0;36m"
y='\033[1;33m' #yellow
b="\e[0;30m"
BGX="\033[42m"
CYAN="\033[96m"
z="\033[96m"
WB='\033[1;36m'
t="\033[1;32m"
f="\033[1;97;41m"
RED='\033[0;31m'
NC='\033[0m'
gray="\e[1;30m"
Blue="\033[0;34m"
green='\033[0;32m'
grenbo="\e[92;1m"
purple="\033[1;95m"
YELL='\033[0;33m'
nama=$(cat /etc/xray/username)
clear

function Newbie_Banner() {
clear
baris_panjang
echo -e "\033[95;1m     \t \t$nama       \033[0m"
baris_panjang
}

function baris_panjang() {
  echo -e "${BlueCyan} ———————————————————————————————————————${Xark}"
}

Newbie_Banner
echo -e " $g 1.$NC ${c}TEMA 1 "$NC     
echo -e " $g 2.$NC ${c}TEMA 2"$NC
baris_panjang
echo ""
read -p "Select From Options [1-2 or x] :  " TEMA
case $TEMA in
1) clear ; wget -q https://raw.githubusercontent.com/diah082/newbie/main/thema/tema1.sh && chmod +x tema1.sh && ./tema1.sh ;;
2) clear ; wget -q https://raw.githubusercontent.com/diah082/newbie/main/thema/tema2.sh && chmod +x tema2.sh && ./tema2.sh ;;
*) tema ;;
esac
